const UPDATE_LOGIN = 'UPDATE_LOGIN';
const LOGIN = 'LOGIN';
const REGISTER = 'REGISTER';
const UPDATE_PROFILE = 'UPDATE_PROFILE';
const FETCH_PROFILE = 'FETCH_PROFILE';
const UPDATE_ROOMS = 'UPDATE_ROOMS';
const FETCH_ROOMS = 'FETCH_ROOMS';
const UPDATE_ROOM_ENTRIES = 'UPDATE_ROOM_ENTRIES';
const FETCH_ROOM_ENTRIES = 'FETCH_ROOM_ENTRIES';
const UPDATE_ROOM_USERS = 'UPDATE_ROOM_USERS';
const FETCH_ROOM_USERS = 'FETCH_ROOM_USERS';
const POST_ENTRY = 'POST_ENTRY';
const UPLOAD_ENTRY = 'UPLOAD_ENTRY';
const POST_ROOM = 'POST_ROOM';
const CREATE_ROOM = 'CREATE_ROOM';
const POST_ADD_ROOM = 'POST_ADD_ROOM';
const JOIN_ROOM = 'JOIN_ROOM';
const SET_ROOM = 'SET_ROOM';
const SET_ENTRY = 'SET_ENTRY';
const SET_URL = 'SET_URL';
const RESET = 'RESET';


export {
  UPDATE_LOGIN,
  LOGIN,
  REGISTER,
  UPDATE_PROFILE,
  FETCH_PROFILE,
  UPDATE_ROOMS,
  FETCH_ROOMS,
  UPDATE_ROOM_ENTRIES,
  FETCH_ROOM_ENTRIES,
  UPDATE_ROOM_USERS,
  FETCH_ROOM_USERS,
  POST_ENTRY,
  UPLOAD_ENTRY,
  POST_ROOM,
  CREATE_ROOM,
  POST_ADD_ROOM,
  JOIN_ROOM,
  SET_ROOM,
  SET_ENTRY,
  SET_URL,
  RESET,
}
